"""Wrap the two source JSON files as plain .js globals.

Why: the finished app must run from file:// with no server, and fetch() of a
local JSON file is blocked by CORS. A <script src> of an assignment is not.
The same files are consumed by the cscript test harness, which has no JSON
object at all. ASCII-only output so every consumer decodes it identically.
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

JOBS = [
    # test-only: the oracle is never loaded by the app itself
    ("oracle_scenarios.json", os.path.join("tests", "oracle_data.js"), "ORACLE_DATA"),
    # runtime: both pages load the graph, so it lives outside tests/
    ("cascade_graph.json", os.path.join("data", "graph_data.js"), "CASCADE_GRAPH"),
]

for src, dst, var in JOBS:
    with open(os.path.join(ROOT, src), encoding="utf-8") as fh:
        data = json.load(fh)
    body = json.dumps(data, ensure_ascii=True, separators=(",", ":"))
    out = os.path.join(ROOT, dst)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="ascii", newline="\n") as fh:
        fh.write("/* GENERATED by tools/make_data_js.py from %s -- do not edit. */\n" % src)
        fh.write("var %s = %s;\n" % (var, body))
    print("wrote %-28s %8.1f KB  (var %s)" % (dst, os.path.getsize(out) / 1024.0, var))
